// <auto-generated />
namespace SchoolSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedrestrictionstomodels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedrestrictionstomodels));
        
        string IMigrationMetadata.Id
        {
            get { return "201706012152297_Added restrictions to models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
